---
- name: "Download Java OpenJDK"
  win_get_url:
    url: "{{ java_openjdk_package }}"
    dest: "{{ temp_dir }}\\java-openjdk-{{ java_openjdk_version }}.msi"

- name: "Installation Java OpenJDK"
  win_shell: |
    Start-Process msiexec.exe -Wait -ArgumentList '/I {{ temp_dir }}\\java-openjdk-{{ java_openjdk_version }}.msi /qb'
  become_method: runas

- name: "Download Java Oracle JDK"
  win_get_url:
    url: "{{ java_oracle_package }}"
    dest: "{{ temp_dir }}\\java-oracle-{{ java_oracle_version }}.msi"

- name: "Installation Java Oracle JDK"
  win_shell: |
    Start-Process msiexec.exe -Wait -ArgumentList '/I {{ temp_dir }}\\java-oracle-{{ java_oracle_version }}.msi /qb'
  become_method: runas

- name: Set an environment variables
  win_environment:
    state: present
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    level: machine
  with_items: "{{ env_vars }}"

- name: Create firewall rules for development access
  win_firewall_rule:
    name: "{{ item.name}}"
    localport: "{{ item.port}}"
    action: allow
    direction: in
    protocol: "{{ item.protocol}}"
    profiles: domain,private,public
    state: present
    enabled: yes
  loop: "{{ dev_firewall }}"
  loop_control:
    label: "{{ item.name }}"

- name: Reboot a machine that takes time to settle after being booted
  win_reboot:
    post_reboot_delay: 120
