plugin: gcp_compute
projects:
- clgx-rqebuild-app-dev-1898
filters:
   - status="RUNNING"
   - labels.purpose="app"
   - labels.environment="dev"
hostnames:
  - name
  - private_ip
compose:
  ansible_host: networkInterfaces[0].networkIP

inventory_ip_type:
- internal
auth_kind: serviceaccount
keyed_groups:
  - key: labels.prefix
