---
- name: visual studio ==> Installed?
  win_stat:
    path: "c:\\VisualStudio2022"
  register: vs_app

- name: Download MS Visual Studio
  win_shell: |
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_professional.exe" -OutFile "{{ temp_dir }}\vs_professional.exe"
  become_method: runas
  when: not vs_app.stat.exists

- name: Install MS Visual Studio with packages
  win_command: '{{ temp_dir }}\vs_professional.exe --passive --wait --norestart --installPath "c:\VisualStudio2022" \
                --includeRecommended
                 --add Microsoft.VisualStudio.Component.CoreEditor \
                 --add Microsoft.VisualStudio.Workload.ManagedDesktop \
                 --add Microsoft.VisualStudio.Workload.NativeCrossPlat
                 --add Microsoft.VisualStudio.Workload.VCTools \
                 --add Microsoft.VisualStudio.Workload.NativeDesktop \
                 --add Microsoft.VisualStudio.Workload.NetWeb \
                 --add Microsoft.NetCore.Component.Runtime.5.0 \
                 --add Microsoft.VisualStudio.Component.ClassDesigner \
                 --add Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL \
                 --add Microsoft.VisualStudio.Component.VC.14.29.16.11.MFC \
                 --add Microsoft.VisualStudio.Component.VC.Redist.MSM \
                 --add Microsoft.VisualStudio.Component.VC.ATLMFC \
                 --add Microsoft.VisualStudio.Component.VC.Llvm.Clang \
                 --add Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset \
                 --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang \
                 --add Component.Linux.CMake \
                 --add Microsoft.VisualStudio.Component.IntelliCode \
                 --add Component.Microsoft.VisualStudio.LiveShare.2022 \
                 --add Microsoft.VisualStudio.Component.NuGet \
                 --add Microsoft.VisualStudio.Component.VC.ASAN \
                 --add Microsoft.VisualStudio.Component.VC.DiagnosticTools \
                 --add Microsoft.VisualStudio.Component.VC.CMake.Project \
                 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
                 --add Microsoft.VisualStudio.Component.VC.ATL \
                 --add Microsoft.VisualStudio.ComponentGroup.VC.Tools.142.x86.x64
                 '
  become_method: runas
  register: vs_pro_rc
  failed_when: vs_pro_rc.rc != 0 and vs_pro_rc.rc != 3010  
  when: not vs_app.stat.exists

- name: Reboot a machine that takes time to settle after being booted
  win_reboot:
    post_reboot_delay: 120

