vault_environment: "nonprd"
organization: "insurance_uw_us"
ecosystem: "rqebuild"

# win_ansible_password: "{{ lookup('hashi_vault', 'secret={{ vault_environment }}/{{ organization }}/secret/data/{{ ecosystem }}/iac')['data']['rqeapp_admin_password']}}"
# ansible_user: admin
# ansible_password: "{{ win_ansible_password }}"
# ansible_port: 5986
# ansible_connection: winrm
# ansible_winrm_scheme: https
# ansible_winrm_transport: ntlm
# ansible_winrm_server_cert_validation: ignore

