plugin: gcp_compute
projects:
- clgx-rqebuild-app-uat-d4e8
filters:
   - status="RUNNING"
   - labels.purpose="app"
   - labels.environment="uat"
hostnames:
  - name
  - private_ip
compose:
  ansible_host: networkInterfaces[0].networkIP

inventory_ip_type:
- internal
auth_kind: serviceaccount
keyed_groups:
  - key: labels.prefix
