- name: "Clear temp dir"
  win_file:
    state: absent
    path: "{{ temp_dir }}"

- name: "Create temp dir"
  win_file:
    state: directory
    path: "{{ temp_dir }}"

- name: Print all the env vars
  debug:
    msg: "{{ ansible_env }}"

- name: Apply regedit database changes
  win_regedit:
    path: "{{ item.path}}"
    name: "{{ item.name}}"
    data: "{{ item.value }}"
    type: dword
  loop: "{{ database_regedit }}"
  loop_control:
    label: "{{ item.name }}"

- name: Disable UAC
  win_shell: |
    New-ItemProperty -Path HKLM:Software\Microsoft\Windows\CurrentVersion\policies\system -Name EnableLUA -PropertyType DWord -Value 0 -Force

# Setup SQL Server Pre-Reqs
- name: Install .NET Framework 3.5
  win_feature:
    name: NET-Framework-Features
    state: present

- name: Install .NET Framework 4.5 Features
  win_feature:
    name: NET-Framework-45-Features
    state: present
    include_sub_features: True

- name: Install Windows Process Activation Service
  win_feature:
    name: WAS
    state: present
    include_sub_features: True

- name: Create firewall rules for mssql access
  win_firewall_rule:
    name: "{{ item.name}}"
    localport: "{{ item.port}}"
    action: allow
    direction: in
    protocol: "{{ item.protocol}}"
    profiles: domain,private,public
    state: present
    enabled: yes
  loop: "{{ database_firewall }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create database accounts
  win_user:
    name: "{{ item.user}}"
    password: "{{ item.password }}"
    password_never_expires: true
    state: present
    groups:
      - Administrators
  loop: "{{ database_users }}"
  loop_control:
    label: "{{ item.user }}"

- name: Copy template preparation script to deploy dir
  win_template:
    src: prepare.ps1.j2
    dest: "{{ temp_dir }}\\ansible_prepare.ps1"

- name: Run preparation script from PD
  win_shell: "{{ temp_dir }}\\ansible_prepare.ps1"
  register: script_output
  become: yes
  become_user: rqe
  become_method: runas
  become_flags: logon_type=interactive logon_flags=with_profile

- name: Print prep installation script output
  debug: 
    msg: "{{ script_output.stdout.split('\r') }}"

- name: Print prep installation script ERRORS output
  debug: 
    msg: "{{ script_output.stderr.split('\r') }}"

- name: Delete autogenerated prep script
  win_file:
    path: "{{ temp_dir }}\\ansible_prepare.ps1"
    state: absent

