rqe_password: "{{ lookup('hashi_vault', 'secret={{ vault_environment }}/{{ organization }}/secret/data/{{ ecosystem }}/iac')['data']['rqe_user_pass']}}"
rqe_svc_password: "{{ lookup('hashi_vault', 'secret={{ vault_environment }}/{{ organization }}/secret/data/{{ ecosystem }}/iac')['data']['rqe_svc_user_pass']}}"

database_users:
      - { user: "rqe", password: "{{ rqe_password }}" }
      - { user: "rqe_svc", password: "{{ rqe_svc_password }}" }
