---
# - import_playbook: playbook-ansible-modules.yml
- hosts: localhost
  roles:  
    - insurance_uw_us-rqebuild-pipeline-iac/ansible-modules

- name: Install OpenSSH
  hosts: _develop
  gather_facts: no
  become_method: runas
  roles:
    - { role: common, tags: [openssh] }
    
- name: Install Visual Studio
  hosts: _develop
  gather_facts: no
  become_method: runas
  roles:
    - { role: develop, tags: [visual-studio] }

- name: Install Java JDK
  hosts: _develop
  gather_facts: no
  become_method: runas
  roles:
    - { role: develop, tags: [java-jdk] }

