vault_environment: "nonprd"
organization: "insurance_uw_us"
ecosystem: "rqebuild"

win_ansible_password: "{{ lookup('hashi_vault', 'secret={{ vault_environment }}/{{ organization }}/secret/data/{{ ecosystem }}/iac')['data']['rqeapp_admin_password']}}"
ansible_user: admin
ansible_password: "{{ win_ansible_password }}"
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_scheme: https
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_read_timeout_sec: 60

rqe_licenses:
  RQE19: "rqe_license_19"
  RQE21: "rqe_license"
  RQE22: "rqe_license"

rqe_major_version: "RQE{{ snapshot_version[:2] }}"
rqe_license_key: "{{ rqe_licenses[rqe_major_version] | default('rqe_license_RQE23') }}"

rqe_license: "{{ lookup('hashi_vault', 'secret={{ vault_environment }}/{{ organization }}/secret/data/{{ ecosystem }}/iac')['data'][rqe_license_key]}}"
